### ISSUE TITLE
Download recording from moodle

### ISSUE THREAD

**Issue by arduran** [openmeetings/openmeetings-moodle-plugin#15]
Hi:
I,ve installed last stable openmeeting version (3.1.1) and testing integration with moodle.
Once, I record a room I've found a issue when click in Download button. I get a 0 byte file.
So, I'm investigating a litle and when plugin code generate the call (line 203 file mod_form.php)

$url = $gateway->getUrl() . "/recordings/$type/" . getOmHash($gateway, array("recordingId" => $openmeetings->om->room_recording_id));

I get in the server side openmeetings.log this output:

 WARN 06-29 13:01:31.540 RequestCycleExtra:346 [http-nio-127.0.0.1-5080-exec-8] - ********************************
 WARN 06-29 13:01:31.542 RequestCycleExtra:347 [http-nio-127.0.0.1-5080-exec-8] - Handling the following exception
org.apache.wicket.util.string.StringValueConversionException: Unable to convert '7170041a047794d9e5aea913eda9f2f9' to a Long value
    at org.apache.wicket.util.string.StringValue.toLongObject(StringValue.java:712) ~[wicket-util-7.2.0.jar:7.2.0]
    at org.apache.wicket.util.string.StringValue.toOptionalLong(StringValue.java:780) ~[wicket-util-7.2.0.jar:7.2.0]
    at org.apache.openmeetings.web.util.RecordingResourceReference.getRecording(RecordingResourceReference.java:115) ~[openmeetings-web-3.1.1.jar:na]
    at org.apache.openmeetings.web.util.RecordingResourceReference.access$000(RecordingResourceReference.java:47) ~[openmeetings-web-3.1.1.jar:na]
    at org.apache.openmeetings.web.util.RecordingResourceReference$1.newResourceResponse(RecordingResourceReference.java:68) ~[openmeetings-web-3.1.1.jar:na]
    at org.apache.wicket.request.resource.AbstractResource.respond(AbstractResource.java:629) ~[wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.handler.resource.ResourceRequestHandler.respond(ResourceRequestHandler.java:105) ~[wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.handler.resource.ResourceReferenceRequestHandler.respond(ResourceReferenceRequestHandler.java:108) ~[wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895) ~[wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64) ~[wicket-request-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.protocol.ws.AbstractUpgradeFilter.processRequestCycle(AbstractUpgradeFilter.java:70) [wicket-native-websocket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core.jar:8.0.26]
    at org.red5.logging.LoggerContextFilter.doFilter(LoggerContextFilter.java:77) [red5-server.jar:1.0.6-RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core.jar:8.0.26]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core.jar:8.0.26]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-embed-core.jar:8.0.26]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526) [tomcat-embed-core.jar:8.0.26]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482) [tomcat-embed-core.jar:8.0.26]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_101]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core.jar:8.0.26]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]
Caused by: java.lang.NumberFormatException: For input string: "7170041a047794d9e5aea913eda9f2f9"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_101]
    at java.lang.Long.parseLong(Long.java:441) ~[na:1.7.0_101]
    at java.lang.Long.<init>(Long.java:702) ~[na:1.7.0_101]
    at org.apache.wicket.util.string.StringValue.toLongObject(StringValue.java:708) ~[wicket-util-7.2.0.jar:7.2.0]
    ... 36 common frames omitted
 WARN 06-29 13:01:31.543 RequestCycleExtra:348 [http-nio-127.0.0.1-5080-exec-8] - ********************************
ERROR 06-29 13:01:31.545 o.a.w.DefaultExceptionMapper:170 [http-nio-127.0.0.1-5080-exec-8] - Unexpected error occurred
org.apache.wicket.util.string.StringValueConversionException: Unable to convert '7170041a047794d9e5aea913eda9f2f9' to a Long value
    at org.apache.wicket.util.string.StringValue.toLongObject(StringValue.java:712) ~[wicket-util-7.2.0.jar:7.2.0]
    at org.apache.wicket.util.string.StringValue.toOptionalLong(StringValue.java:780) ~[wicket-util-7.2.0.jar:7.2.0]
    at org.apache.openmeetings.web.util.RecordingResourceReference.getRecording(RecordingResourceReference.java:115) ~[openmeetings-web-3.1.1.jar:na]
    at org.apache.openmeetings.web.util.RecordingResourceReference.access$000(RecordingResourceReference.java:47) ~[openmeetings-web-3.1.1.jar:na]
    at org.apache.openmeetings.web.util.RecordingResourceReference$1.newResourceResponse(RecordingResourceReference.java:68) ~[openmeetings-web-3.1.1.jar:na]
    at org.apache.wicket.request.resource.AbstractResource.respond(AbstractResource.java:629) ~[wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.handler.resource.ResourceRequestHandler.respond(ResourceRequestHandler.java:105) ~[wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.handler.resource.ResourceReferenceRequestHandler.respond(ResourceReferenceRequestHandler.java:108) ~[wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895) ~[wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64) ~[wicket-request-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.protocol.ws.AbstractUpgradeFilter.processRequestCycle(AbstractUpgradeFilter.java:70) [wicket-native-websocket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284) [wicket-core-7.2.0.jar:7.2.0]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core.jar:8.0.26]
    at org.red5.logging.LoggerContextFilter.doFilter(LoggerContextFilter.java:77) [red5-server.jar:1.0.6-RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core.jar:8.0.26]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core.jar:8.0.26]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core.jar:8.0.26]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-embed-core.jar:8.0.26]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526) [tomcat-embed-core.jar:8.0.26]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482) [tomcat-embed-core.jar:8.0.26]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_101]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core.jar:8.0.26]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]
Caused by: java.lang.NumberFormatException: For input string: "7170041a047794d9e5aea913eda9f2f9"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_101]
    at java.lang.Long.parseLong(Long.java:441) ~[na:1.7.0_101]
    at java.lang.Long.<init>(Long.java:702) ~[na:1.7.0_101]
    at org.apache.wicket.util.string.StringValue.toLongObject(StringValue.java:708) ~[wicket-util-7.2.0.jar:7.2.0]
    ... 36 common frames omitted

I verify 7170041a047794d9e5aea913eda9f2f9 string is the hash moodle plugin sent. Not sure but the hash it's intend to convert in Long value, and a exception is raised.

**Comment by solomax** [comment]
sorry for the late reply, was on vacation

Thanks for the report
will try to reproduce/fix it ASAP

**Comment by solomax** [comment]
https://issues.apache.org/jira/browse/OPENMEETINGS-1432

**Comment by mwuttke** [comment]
Hello Maxim,

I've updated the plugin page: https://moodle.org/plugins/mod_openmeetings
Please can you change next time also the build.xml file? ;-)

Thanks & Greetings,
Michael

**Comment by solomax** [comment]
Sorry, forgot about it :(
